# Generated by Django 4.2.4 on 2023-08-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0003_remove_product_product_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
