# Generated by Django 4.2.4 on 2023-08-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0007_product_product_status_product_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
