# Generated by Django 4.2.4 on 2023-09-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0011_alter_cartorder_price_alter_cartorderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
